### ISSUE TITLE
Rebase on stricter types for fields?

### ISSUE THREAD

**Issue by roll** [frictionlessdata/dplib-py#11]
# Overview

As @khusmann suggested, the type system will be safer if we use a type-based model for fields. Currently, there is a shared `Field` model for simplifying mappings (e.g. Data Package <> CKAN) but there might be a way to keep the simplicity and have more type-safe field models.

**Comment by khusmann** [comment]
I think type-safe descriptor models will make the project much more robust (via static analysis) and easier for developers to use (via code editor auto-completion) in the long run.

In particular, I'm looking for things like the ability to create an `integer` field object, and then when I try to put constraints on it, I my editor will autocomplete all the possible constraints for `integer` fields (and will highlight errors if I try to add constraints that don't apply, like `minLength` / `maxLength`).

Are there any specific barriers you're seeing for this (i.e. where enforcing type-safety reduces simplicity-of-use)? I may be able to suggest some approaches / design patterns that could allow us to have both type safety and an API that's easy to use with mappers like CKAN.

**Comment by roll** [comment]
Thanks @khusmann!

I don't think there are major barriers, so I'm going to analyze it and if I'm stuck I'll ask you for help :beers:
